/*
 * Licensed Materials - Property of IBM
 *
 * L-MCOS-96LQPJ
 *
 * (C) Copyright IBM Corp. 2002, 2013. All rights reserved.
 *
 * US Government Users Restricted Rights- Use, duplication or 
 * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

#ifndef __STDDACLCODES_H__
#define __STDDACLCODES_H__


#define ST_DDA_CL_SESSION_ALREADY_EXISTS        0x1002
#define ST_DDA_CL_SESSION_DOES_NOT_EXIST        0x1003
#define ST_DDA_CL_DB_ERROR                      0x1004
#define ST_DDA_MSG_TOO_LONG                     0x1005
#define ST_DDA_SESSION_CREATION_DECLINED        0x1006
#define ST_DDA_SESSION_CLOSED_BY_SERVER         0x1007
#define ST_DDA_MSG_CHANGED                      0x1008


#define ST_DDA_MAX_MSG_LEN            11000
#define ST_DDA_MAX_NAME_LENGTH        256
#define ST_DDA_MAX_STR_LEN            1024
#define MESSAGE_SIZE                  2048

#define CL_SUFFIX						  ".dat"
#define LIBRARY_SECTION			  "Library"
#define DEFAULT_LIB_PATH  	  "CLData"
#define CL_LIBRARY_PATH			  "BB_CL_LIBRARY_PATH"
#define CL_INI_FILE_NAME      "chatlogging.ini"
#define CL_TRACE_FILE_NAME    "Trace/StChatLog.txt"
#define CL_PREFIX_NAME        "StChatLog"

#define DEBUG_SECTION "Debug"
#define CHAT_LOGGING_SECTION "ChatLogging"
#define CL_BAN_CHAT_BETWEEN_USERS "CL_BAN_CHAT_BETWEEN_USERS"
#define CL_REPLACE_STRINGS_IN_MSG "CL_REPLACE_STRINGS_IN_MSG"
#define CL_REPLACE_STRINGS_IN_MSG_WARNING "CL_REPLACE_STRINGS_IN_MSG_WARNING"
#define CL_REPLACE_STRINGS_IN_MSG_WARNING_RICH_TEXT "CL_REPLACE_STRINGS_IN_MSG_WARNING_RICH_TEXT"
#define CL_DELETE_MSG_WITH_STRING "CL_DELETE_MSG_WITH_STRING"
#define CL_WARNING_ON_DELETED_MSG "CL_WARNING_ON_DELETED_MSG"
#define CL_WARNING_ON_DELETED_MSG_RICH_TEXT "CL_WARNING_ON_DELETED_MSG_RICH_TEXT"
#define CL_BAN_CHAT_WARNING_MSG   "CL_BAN_CHAT_WARNING_MSG"
#define CL_CHAT_START_DISCLAIMER  "CL_CHAT_START_DISCLAIMER"
#define CL_CHAT_START_DISCLAIMER_RICH_TEXT  "CL_CHAT_START_DISCLAIMER_RICH_TEXT"

#define CL_CHAT_MONGODB_HOST "CL_CHAT_MONGODB_HOST"
#define CL_CHAT_MONGODB_PORT "CL_CHAT_MONGODB_PORT"
#define CL_CHAT_MONGODB_USER "CL_CHAT_MONGODB_USER"
#define CL_CHAT_MONGODB_PASSWORD "CL_CHAT_MONGODB_PASSWORD"
#define CL_CHAT_MONGODB_DBNAME "CL_CHAT_MONGODB_DBNAME"


#endif //__STDDACLCODES_H__
